apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test

configurations:
- rollout-transform.yaml

images:
- digest: sha256:a6187d37a7996f40f9c17f0b91f01c82cc5fcf7112f9b334f87b80f3e53c0b5d
  name: python-demo-rollout
  newName: harbor.shared.lab.pksdemo.net/tanzu/apps/python-demo-rollout

resources:
- python-demo-deploy.yaml
- python-demo-rollout-svc.yaml
